name: "gold-watcher"
version: "3.7"
services:
  postgres:
    container_name: "goldwatcher-db"
    image: "postgres:16.2-alpine3.19"
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - "./../docker-volumes/pgdata:/var/lib/postgresql/data/"
      - "./custom-postgresql.conf:/etc/postgresql/postgresql.conf"
    environment:
      - POSTGRES_PASSWORD=asdqwe1234
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
