name: "goldwatcher"
version: "3.7"
services:
  db:
    container_name: goldwatcher-db
    image: postgres:16.2-alpine3.19
    expose:
      - 5433
    ports:
      - 5433:5433
    volumes:
      - ./../docker-volumes/pgdata:/var/lib/postgresql/data/
      - ./custom-postgresql.conf:/etc/postgresql/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=asdqwe1234
      - POSTGRES_DB=goldwatcher
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  goldwatcher_app:
    container_name: goldwatcher_app
    image: goldwatcher:latest
    depends_on:
      - db
    env_file:
      - path: ./.env
        required: true
